AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS CloudFormation template for payment state machine

Parameters:
  DatabaseClusterDomain:
    Type: String
  PaymentSystemDatabaseName:
    Type: String
  OrderDataGetter:
    Type: String


Resources:

  DatabaseMongoSecurityGroup:
    Properties:
      GroupDescription: Group to access mongodb vpc
      GroupName: DatabaseMongoSecurityGroup
      VpcId: vpc-0fab92b867b73a59f
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          FromPort: '-1'
          ToPort: '-1'
          IpProtocol: -1
    Type: 'AWS::EC2::SecurityGroup'

  CreateNetworkInterfacePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ec2:CreateNetworkInterface
              - ec2:DescribeNetworkInterfaces
              - ec2:DetachNetworkInterface
              - ec2:DeleteNetworkInterface
            Effect: Allow
            Resource: '*'
        Version: '2012-10-17'

  AllLogsAccessPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "logs:*"
            Resource: "arn:aws:logs:*:*:*"

  CheckProductAvailabilityLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Ref AllLogsAccessPolicy
        - !Ref CreateNetworkInterfacePolicy
      RoleName: CheckProductAvailabilityLambdaRole

  CheckProductAvailabilityLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/check_product_availability
      Handler: check_product_availability_lambda.lambda_handler.lambda_handler
      Runtime: python3.8
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          PAYMENT_SYSTEM_DATABASE_NAME: !Ref PaymentSystemDatabaseName
          ORDER_DATA_GETTER: !Ref OrderDataGetter
          DATABASE_CLUSTER_DOMAIN: !Ref DatabaseClusterDomain
      VpcConfig:
        SecurityGroupIds:
          - !Ref DatabaseMongoSecurityGroup
        SubnetIds:
          - subnet-0f606614dd53ab804
      Role: !GetAtt CheckProductAvailabilityLambdaRole.Arn
